# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: common.env
steps:
  - script: 'wget https://releases.hashicorp.com/terraform/0.13.5/terraform_0.13.5_linux_amd64.zip;
  unzip terraform_0.13.5_linux_amd64.zip;
  echo "loading terragrunt";
  wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.26.0/terragrunt_linux_amd64;
  mv terragrunt_linux_amd64 terragrunt;
  chmod +x terragrunt;
  mkdir bin; mv terraform bin/.;
  mv terragrunt bin/.;
  export PATH=$PWD/bin:$PATH;
  cd dev/aks-storage;
  echo "path = $PATH";
  az account list'
  #az account set --subscription "Azure for Students";
  #echo "initializing terragrunt";
  #terragrunt init; terragrunt plan -out test.plan; terragrunt apply test.plan'

# steps:
#- script: echo Hello, world!
#  displayName: 'Run a one-line script'

#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'
