stages:
- stage: init
  jobs:
  - job: 
    steps:
    - task: installTerragrunt@0
      inputs:
        terragruntversion: '0.18.4'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          terragrunt init