stages:
- stage: init
  jobs:
  - job: 
    steps:
    - task: installTerragrunt@0
      inputs:
        terragruntversion: '0.18.4'
    - task: TerragruntInit@1
      inputs:
        script: 'terragrunt init'